# docker/Dockerfile
FROM python:3.11-slim

WORKDIR /app

# copiar requirements
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app

ENV PYTHONUNBUFFERED=1
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
